name: Build & Release

on:
  push:
    branches: ["master"]

jobs:
  build:
    name: Build

    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm

      - name: Install dependencies
        run: cd gui && pnpm install && cd .. && pnpm install

      - name: Build
        run: cd gui && pnpm build && cd .. && pnpm electron-builder --win --x64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release
          path: ./dist/roplat-gui 1.0.0.exe
